FROM eclipse-temurin:25-jdk AS build
WORKDIR /app

COPY gradlew .
RUN chmod +x gradlew
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN ./gradlew build --no-daemon -x test || return 0

COPY src src
RUN ./gradlew build --no-daemon -x test

FROM eclipse-temurin:25-jre
WORKDIR /app

COPY --from=build /app/build/libs/*-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
