spring.application.name=Backend

#.env file location
spring.config.import=optional:file:../.env

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME:bus}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
